### ISSUE TITLE
Hi sir. Sorry for inconvenience 

### ISSUE THREAD

**Issue by Mike1250** [McMCCRU/gx6605s_linux_fw_build#3]
I have a new model of gx6605s and I want to try your mini sat ip but after I flash it to my stb it show in UART console that message :  kernel  panic -  not syncing : vfs:unable to mount rootfs on unknown-block(0;0)
Any idea how to fix it?

And thanks in advance

**Comment by McMCCRU** [comment]
Hi! Very little information. Probably something was done wrong or something is missing. I have not encountered such a problem.

**Comment by Mike1250** [comment]
thank you for your reply .
i fixed it by flash via programmer but now i ran into another problem 
the firmware did not recognize my tuner because its not rda8515m . my stb is a new model which launched in 2021 it called senator b200
if there is any possibility to fix i appreciate it . and here is the full log 

..........................................................

GxLoader v1.9 20200317

cpu family      : CSKY
chip model      : gx6605s
board type      : generic
memory size     : 64 MB
Flash type      : w25q32
Flash size      : 4 MB
uImage_load_kernel.

Decompress kernel ...ok
The total boot time is: 1 s (1902 ms)
[    0.000000] Linux version 2.6.27.55 (igor@igor-GL553VE) (gcc version 4.5.1 (C-SKY Tools V2.8.01-gx-sp9(UClibc), ABIV1, B20170724) ) #3 Sun May 24 19:40:53 MSK 2020
[    0.000000] CPU revision is: 0x102816b2 (CK610MA)
[    0.000000] Determined physical RAM map:
[    0.000000] User-defined physical RAM map:
[    0.000000]  memory: 04000000 @ 10000000 (usable)
[    0.000000] Zone PFN ranges:
[    0.000000]   Normal   0x00010000 -> 0x00014000
[    0.000000] Movable zone start PFN for each node
[    0.000000] early_node_map[1] active PFN ranges
[    0.000000]     0: 0x00010000 -> 0x00014000
[    0.000000] Built 1 zonelists in Zone order, mobility grouping off.  Total pages: 16256
[    0.000000] Kernel command line: mem=64M console=ttyS0,115200 init=/init chipid=0x6605 root=/dev/mtdblock3 mtdparts=m25p80:64k@0m(BOOT),64k@64k(TABLE),960k@128k(KERNEL),2752k@1088k(ROOTFS),256k@3840k(DATA)
[    0.000000] PID hash table entries: 256 (order: 8, 1024 bytes)
[    0.000000] Console: colour dummy device 80x25
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.010000] Memory: 62804k/65536k available (1539k kernel code, 2676k reserved, 485k data, 68k init, 0k highmem)
[    0.010000] SLUB: Genslabs=12, HWalign=16, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.010000] Calibrating delay loop... 593.10 BogoMIPS (lpj=2965504)
[    0.240000] Mount-cache hash table entries: 512
[    0.240000] net_namespace: 288 bytes
[    0.240000] NET: Registered protocol family 16
[    0.240000] GX3XXX: Initialising architecture
[    0.240000] gx_chip_id: 0x6605
[    0.260000] SCSI subsystem initialized
[    0.260000] usbcore: registered new interface driver usbfs
[    0.260000] usbcore: registered new interface driver hub
[    0.260000] usbcore: registered new device driver usb
[    0.290000] NET: Registered protocol family 2
[    0.380000] IP route cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.380000] TCP established hash table entries: 2048 (order: 2, 16384 bytes)
[    0.380000] TCP bind hash table entries: 2048 (order: 1, 8192 bytes)
[    0.380000] TCP: Hash tables configured (established 2048 bind 2048)
[    0.380000] TCP reno registered
[    0.410000] NET: Registered protocol family 1
[    0.410000] squashfs: version 3.4 (2008/08/26) Phillip Lougher
[    0.410000] squashfs: LZMA suppport for slax.org by jro
[    0.410000] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 254)
[    0.410000] io scheduler noop registered
[    0.410000] io scheduler anticipatory registered
[    0.410000] io scheduler deadline registered
[    0.410000] io scheduler cfq registered (default)
[    0.980000] Nationalchip IRR Driver
[    0.980000] input: goxceed remote control as /class/input/input0
[    1.010000] Nationalchip gpio Driver
[    1.010000] Serial: 8250/16550 driver4 ports, IRQ sharing disabled
[    1.020000] serial8250.0: ttyS0 at MMIO 0x403000 (irq = 15) is a 16550A
[    1.020000] console [ttyS0] enabled
[    1.040000] loop: module loaded
[    1.050000] usbcore: registered new interface driver catc
[    1.050000] catc: v2.8 CATC EL1210A NetMate USB Ethernet driver
[    1.060000] usbcore: registered new interface driver kaweth
[    1.070000] pegasus: v0.6.14 (2006/09/27), Pegasus/Pegasus II USB Ethernet driver
[    1.070000] usbcore: registered new interface driver pegasus
[    1.080000] rtl8150: rtl8150 based usb-ethernet driver v0.6.2 (2004/08/27)
[    1.090000] usbcore: registered new interface driver rtl8150
[    1.090000] usbcore: registered new interface driver r8152
[    1.100000] usbcore: registered new interface driver asix
[    1.110000] usbcore: registered new interface driver ax88179_178a
[    1.110000] usbcore: registered new interface driver cdc_ether
[    1.120000] usbcore: registered new interface driver dm9620
[    1.120000] usbcore: registered new interface driver gl620a
[    1.130000] usbcore: registered new interface driver net1080
[    1.140000] usbcore: registered new interface driver plusb
[    1.140000] usbcore: registered new interface driver rndis_host
[    1.150000] usbcore: registered new interface driver cdc_subset
[    1.160000] usbcore: registered new interface driver MOSCHIP usb-ethernet driver
[    1.160000] usbcore: registered new interface driver qf9700
[    1.170000] SCSI Media Changer driver v0.25
[    1.180000] m25p80 spi0.0: w25q32 (4096 Kbytes)
[    1.190000] 6 cmdlinepart partitions found on MTD device m25p80
[    1.190000] Creating 6 MTD partitions on "m25p80":
[    1.200000] 0x00000000-0x00010000 : "BOOT"
[    1.200000] 0x00010000-0x00020000 : "TABLE"
[    1.210000] 0x00020000-0x00110000 : "KERNEL"
[    1.220000] 0x00110000-0x003c0000 : "ROOTFS"
[    1.230000] 0x003c0000-0x00400000 : "DATA"
[    1.230000] 0x00010000-0x003c0000 : "UPDATE"
[    1.240000] Initializing USB Mass Storage driver...
[    1.250000] usbcore: registered new interface driver usb-storage
[    1.250000] USB Mass Storage support registered.
[    1.260000] usbcore: registered new interface driver usbserial
[    1.260000] usbserial: USB Serial support registered for generic
[    1.270000] usbcore: registered new interface driver usbserial_generic
[    1.280000] usbserial: USB Serial Driver core
[    1.280000] usbserial: USB Serial support registered for cp2101
[    1.290000] usbcore: registered new interface driver cp2101
[    1.290000] cp2101: Silicon Labs CP2101/CP2102 RS232 serial adaptor driver v0.07
[    1.300000] usbserial: USB Serial support registered for debug
[    1.310000] usbcore: registered new interface driver debug
[    1.310000] usbserial: USB Serial support registered for FTDI USB Serial Device
[    1.320000] usbcore: registered new interface driver ftdi_sio
[    1.330000] ftdi_sio: v1.4.3:USB FTDI Serial Converters Driver
[    1.340000] usbserial: USB Serial support registered for GSM modem (1-port)
[    1.340000] usbcore: registered new interface driver option
[    1.350000] option: USB Driver for GSM modems: v0.7.2
[    1.350000] usbserial: USB Serial support registered for pl2303
[    1.360000] usbcore: registered new interface driver pl2303
[    1.370000] pl2303: Prolific PL2303 USB to serial adaptor driver
[    1.370000] i2c /dev entries driver
[    1.380000] nc watchdog init success.
[    1.390000] TCP cubic registered
[    1.390000] NET: Registered protocol family 17
[    1.400000] VFS: Mounted root (squashfs filesystem) readonly.
[    1.410000] Freeing unused kernel memory: 68k freed
[    1.420000] Warning: unable to open an initial console.
[    4.450000] minifs filesystem mount success!
[    4.790000] hello, panel!
[    5.030000] gxav_module_init: ok!
[    5.580000] DVB: registering new adapter (gxdvb)
[    5.580000] fe_profile.demod_type = 8
[    5.580000] fe_profile.demod_i2c_id = 0
[    5.590000] fe_profile.demod_chip_addr = 0xe4
[    5.590000] fe_profile.tuner_type = 55
[    5.600000] fe_profile.tuner_i2c_id = 0
[    5.600000] fe_profile.tuner_chip_addr = 0x18
[    5.600000]
[    5.600000] DEMOD, tuner register
[    5.620000] gx3211_init!!
[    5.620000]
[    5.620000] GX3211_GXDemod_Chanl_Rst
[    5.640000]
[    5.640000] DEMOD, GX3211_GXDemod_Init
[    5.640000] gx_i2c_open_dev(),find active i2c device,i2c_devid=0
[    5.800000] gx31x0_i2c_xfer() error : chipaddr: 0x0c, addr(one byte): 0x00, operatin: READ,
[    5.810000] RX: Error during I2C_RDWR ioctl with error code: -121
[    5.820000] RDA5815M I2C read error, ADDR: 24(0x18), REG:0(0x00), DATA: 0(0x00)
[    5.820000] read rda581x chip id err!
[    6.010000] gx31x0_i2c_xfer() error : chipaddr: 0x0c, addr(one byte): 0x01, operatin: READ,
[    6.010000] RX: Error during I2C_RDWR ioctl with error code: -121
[    6.020000] RDA5815M I2C read error, ADDR: 24(0x18), REG:1(0x01), DATA: 0(0x00)
[    6.030000] read rda581x chip id err!
[    6.030000] Read rda581x chip id 0x0 0x0
[    6.040000] DVB: registering frontend 0 (Nationalchip GX3211 DVB-C S2)...
[    6.130000] hello, GPIO!
[    6.240000] EHCI-NationalChip EHCI-NationalChip.0: EHCI-NationalChip
[    6.270000] EHCI-NationalChip EHCI-NationalChip.0: new USB bus registered, assigned bus number 1
[    6.300000] EHCI-NationalChip EHCI-NationalChip.0: irq 59, io mem 0x00900000
[    6.320000] EHCI-NationalChip EHCI-NationalChip.0: USB 0.0 started, EHCI 1.00, driver 10 Dec 2004
[    6.340000] usb usb1: configuration #1 chosen from 1 choice
[    6.360000] hub 1-0:1.0: USB hub found
[    6.360000] hub 1-0:1.0: 2 ports detected
[    6.980000] ohci_hcd_gx_drv_probe, a00000.
[    6.980000] OHCI-NationalChip OHCI-NationalChip.0: OHCI-NationalChip
[    7.010000] OHCI-NationalChip OHCI-NationalChip.0: new USB bus registered, assigned bus number 2
[    7.010000] OHCI-NationalChip OHCI-NationalChip.0: irq 58, io mem 0x00a00000
[    7.120000] usb usb2: configuration #1 chosen from 1 choice
[    7.170000] hub 2-0:1.0: USB hub found
[    7.170000] hub 2-0:1.0: 1 port detected
[    7.340000] ohci_hcd_gx_drv_probe, b00000.
[    7.340000] OHCI-NationalChip OHCI-NationalChip.1: OHCI-NationalChip
[    7.400000] OHCI-NationalChip OHCI-NationalChip.1: new USB bus registered, assigned bus number 3
[    7.410000] OHCI-NationalChip OHCI-NationalChip.1: irq 57, io mem 0x00b00000
[    7.520000] usb usb3: configuration #1 chosen from 1 choice
[    7.560000] hub 3-0:1.0: USB hub found
[    7.560000] hub 3-0:1.0: 1 port detected
[    7.950000] usb 3-1: new full speed USB device using OHCI-NationalChip and address 2
[    8.010000] Monitor Driver, (c) 2013 Technologies
[    8.230000] usb 3-1: configuration #1 chosen from 1 choice
[    8.340000] Init Internal TS interface for gx6605s.
[    8.340000] Use Internal TS interface in force parallel mode!!!!
[    8.850000] eth0: register 'qf9700' at usb-OHCI-NationalChip-1, QF9700 USB Ethernet, 00:e0:4c:53:44:58
[   10.970000] eth0: link up, 100Mbps, full-duplex, lpa 0xFFFF
~ # [   14.350000] tune mode = 0
[   14.350000]
[   14.350000] GX3211_GXDemod_Chanl_Rst
[   14.370000]
[   14.370000] MODE SELECT---------------------
[   14.370000]
[   14.370000] GX3211_GX1132_Init_Chip

**Comment by McMCCRU** [comment]
You need to know the tuner chip and its i2c address.
Example for K1 Koqit mini:
RDA5815M
FE_PROFILE="|8:0:0xe4:55:0:0x18:&1:1:2:0:0:1"
```
[ 5.590000] fe_profile.tuner_type = 55
[ 5.600000] fe_profile.tuner_i2c_id = 0
[ 5.600000] fe_profile.tuner_chip_addr = 0x18
```
AV2018
FE_PROFILE="|8:0:0xe4:41:0:0xc6:&1:1:2:0:0:1"
Format:
`"|<demod type>:<demod at i2c>:<demod i2c addr>:<tuner type>:<tuner at i2c>:<tuner i2c addr>:[&iq_swap:hv:tspni_cfg:bsp:lnb_invert]`
https://github.com/McMCCRU/minisatip-gx/issues/2#issuecomment-742761632

**Comment by McMCCRU** [comment]
Previously, this initialization string could be obtained from the logs in the console, this is not the case in new firmware.

**Comment by Mike1250** [comment]
Thnx. Appreciate it
